import { describe, expect, it } from "vitest";
import { LATEST, RELEASES } from "../data/releases";

// The ledger is generated by tools/sync-releases.mjs. Its first double-digit
// minor version (v1.10.0) exposed a lexicographic sort that put the newest
// release below v1.9.0 — these pin the properties the page depends on so the
// next such boundary fails here rather than on the deployed changelog.

const parts = (tag: string) => tag.replace(/^v/, "").split(".").map(Number);

describe("release ledger", () => {
  it("is ordered newest first by version, not by string", () => {
    for (let i = 1; i < RELEASES.length; i++) {
      const [aMaj, aMin, aPatch] = parts(RELEASES[i - 1].tag);
      const [bMaj, bMin, bPatch] = parts(RELEASES[i].tag);
      const newer =
        aMaj > bMaj || (aMaj === bMaj && (aMin > bMin || (aMin === bMin && aPatch > bPatch)));
      expect(newer, `${RELEASES[i - 1].tag} should sort above ${RELEASES[i].tag}`).toBe(true);
    }
  });

  it("marks exactly one release live, and it is the newest", () => {
    const live = RELEASES.filter((r) => r.isLatest);
    expect(live).toHaveLength(1);
    expect(live[0].tag).toBe(RELEASES[0].tag);
    expect(LATEST.tag).toBe(RELEASES[0].tag);
  });

  it("gives every release a dated, explained entry", () => {
    for (const release of RELEASES) {
      expect(release.tag, "tag shape").toMatch(/^v\d+\.\d+\.\d+$/);
      expect(release.date, `${release.tag} date`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(release.title.trim().length, `${release.tag} title`).toBeGreaterThan(0);
      expect(release.summary.trim().length, `${release.tag} summary`).toBeGreaterThan(40);
    }
  });
});
